### ISSUE TITLE
logo concepts

### ISSUE THREAD

**Issue by jonschlinkert** [enquirer/artwork#1]
#1

![enquirer-01-high-resolution-dark](https://cloud.githubusercontent.com/assets/383994/18683818/d1623a54-7f3f-11e6-99ee-b9198e72dcd5.png)

![enquirer-01](https://cloud.githubusercontent.com/assets/383994/18683822/d181fc36-7f3f-11e6-9a25-4a361130dd9d.jpg)

<br>
<br>
<br>
#2

![enquirer-02-high-resolution-dark](https://cloud.githubusercontent.com/assets/383994/18683820/d170f3e6-7f3f-11e6-9919-f403e5fd9f73.png)

![enquirer-02](https://cloud.githubusercontent.com/assets/383994/18683823/d18548c8-7f3f-11e6-898d-4971c9ccb9cb.jpg)

**Comment by jonschlinkert** [comment]
I love the second design overall. But the icon in the first design can stand alone more easily. Not sure which one to choose.

**Comment by doowb** [comment]
I like the logo in 1 also. I'm not sure if I like the `Q` in the second one. I like it in the smaller font sizes, but not in the larger font size.

**Comment by jonschlinkert** [comment]
> I like it in the smaller font sizes, but not in the larger font size.

yeah I think most of the time it will be smaller.

**Comment by tunnckoCore** [comment]
I like the first one too :) It's awesome, one beer for the creator :D

**Comment by jonschlinkert** [comment]
case closed!
